# -*- coding: utf-8 -*-
"""Despliegue_ataque.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Sfh2ANr519igGVSM7ZzSS76RQBtnxYa

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-class.pkl'
modelo_final, labelencoder,variables,min_max_scaler = pickle.load(open(filename, 'rb'))

modelo_final

#Cargamos los datos futuros
data = pd.read_excel("nuevos_pacientes.xlsx")
data.head()

#Interfaz gráfica


#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de ataque al corazón')

age = st.slider('Edad', min_value=1, max_value=82, value=45, step=1)
hypertension = st.selectbox('¿Tiene hipertensión?', ["Yes", "No"])
heart_disease = st.selectbox('¿Tiene enfermedad cardíaca?', ["Yes", "No"])
ever_married = st.selectbox('¿Alguna vez se ha casado?', ["Yes", "No"])
avg_glucose_level = st.slider('Nivel promedio de glucosa', min_value=55.0, max_value=272.0, value=106.0, step=0.1)

#Etiquetas amigables -> valores exactos del dataset (con las comillas incluidas)
opciones_fumador = {
    'Nunca ha fumado': "'never smoked'",
    'Fumaba antes': "'formerly smoked'",
    'Fuma': 'smokes',
    'Desconocido': 'Unknown'
}
fumador = st.selectbox('Hábito de fumar', list(opciones_fumador.keys()))
smoking_status = opciones_fumador[fumador]


#Dataframe
datos = [[age, hypertension, heart_disease, ever_married, avg_glucose_level, smoking_status]]
data = pd.DataFrame(datos, columns=['age', 'hypertension', 'heart_disease', 'ever_married',
                                    'avg_glucose_level', 'smoking_status']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['age', 'hypertension', 'heart_disease', 'ever_married',
                                    'avg_glucose_level', 'smoking_status'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
data_preparada[['age','avg_glucose_level']]= min_max_scaler.transform(data_preparada[['age','avg_glucose_level']])
data_preparada.head()

"""# **Predicciones**"""

#Hacemos la predicción con el Tree
Y_pred = modelo_final.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 0.8% (mape: error porcentual)")